package org.racetrack.analyzer;

import java.io.*;

public class MapCreator {

  public static void main(String[] args) {

    String title = "Arecibo";
    String mapCode = "WWWWWWWWWWWWWWWWWWWWWWWWWWOOOOOONONONONOOOOOOOOOOWWOONONOOOOONONOOOOOOONOOWWNOOONOOONOOONOONONNOONOWWNONONONONONONONOONOONOOWWOOOOOOOOOOOOOOOOOOOOOOOWWOOOOOOOOOOOOWWOOOOOOOOOWWOOOOOOOOOOWWOWOOOOOOOOOWWOOOOOOOOOOWWOWOOOOOOOOOWWOOOOOOOOOWOWOWOOOOOOOOOWWOOOOOOOOOWWWWWOOOOOOOOOWWOOOOOOOOOOOOOOOOOOOOOOOWWXXOOOOXXXOOOXXOOOOXXOOOWWXOOOOOOOOOOOOOXXOOXOOOOWWXXOXOOOXXOOOXXOOOOXXOXOWWXXXXXOXXXXXOXXXXXOXXXXXWWOOOOOOOOOOOOOOOOOOOOOOOWWOOOXOOOOOOOOOOOOOOOOOXOWWOOOOOOOOOOOOOOOOOOOOOOOWWOOOOXOOOOOOOOOOOOOOOOOXWWXXXXXOOOOOOOOOOOOOXXXXXWWOOOOOOOOOOOOOOOOOOOOOOOWWXXOOOOXXOOOOXXXOOOXXOOOWWXOOOOOOOXOOOOOOOOOXOOOOWWXXOXOOOOXXOOOXXXOOXXOXOWWXXXXXOXXXXXOXXXXXOXXXXXWWOOOOOOOOOOOOOOOOOOOOOOOWWOOOXOOOOOONNOOOOOOOOOXOWWOOOOOOOOOONNOOOOOOOOOOOWWOOOOXOOOOONNOOOOOOOOOOXWWXXXXXOOOOONNOOOOOOXXXXXWWOOOOOOOOOONNOOOOOOOOOOOWWOOWOOOOOOOONOOOOOOOOWOOWWOOOWOOOOOONNOOOOOOOWOOOWWOOOOWWOOOONNOOOOOOWOOOOWWOOOOOOWWOOONOOOOWWOOOOOWWOOOOOOOOOONNOOWWOOOOOOOWWOOOOOOWWOOONOOOOWWOOOOOWWOOOOWWOOOONNOOOOOOWOOOOWWOOOWOOOOOONOOOOOOOOWOOOWWOOWOOOOOOONNOOOOOOOOWOOWWOWOOOOOOOONNOOOOOOOOWOOWWOWOOOOOOOOONOOOOOOOWOOOWWOOWOOOOOOOPOOOOOOOWOOOOWWOOOWOOOOOOOOOOOOWWOOOOOWWOOOOWWOOOOOOOOWWOOOOOOOWWOOWOOOWWWOWOWWOOOOOOOOOWWOOWOOOOOOOWOOOOOOOOOOOOWWOOWOOOOOWWWWWOOOOOOOOOOWWOOWOOOOWOWWWOWOONONNONNWWOOOOOOWOOWWWOOWOONNNNNNWWNONNNOOOOWWWOOOOONNONNNWWOOOOOOOOOWOWOOOOONNNONNWWOOWOOOOOOWOWOOOOONNNNNNWWOOWOOOOOOWOWOOOOONNOOOOWWOOWOOOOOWWOWWOOOOOOOOOOWWOOOOOOOOOOOOOOOOOOOOOOOWWOOGGGOOOOOGOOOOOOOOOOOOWWOOGGGOGOGOOOGOGOGOGOGOGWWOOGGGOOOOOOOOOGOGOGOGOOWWOOOOOOOOOOOOOOGOGOOOOOOWWOOOOOOOOWWWWWOOOOOOOOOOWWOOOOOOWWWWWWWWWOOOOOOOOWWOOOOWWWOOOOOOOWWWOOOOOOWWOOOWWOOOOOOOOOOOWWOOOOOWWOOWWOWOOOOOOOOOWOWWOOOOWWOWWOOWWOOOOOOOWWOOWWOOOWWOWOOOWOWOOOOOWOWOOOWOOOWWOWOOOWOOWOOOWOOWOOOWOOOWWOOOOOWOOOWOWOOOWOOOOOOOWWOOOOOWOOOOWOOOOWOOOOOOOWWOOOOOWOOOOOOOOOWOOOOOOOWWOOOOOOONOONONOOOOOOOOOOWWOWWWWOONNNNNONOOWWWWOOOWWWWWWWWWWWWWWWWWWWWWWWWWW";
    int cols = 25;

    int rows = mapCode.length() / cols;

    if (mapCode.length() % cols != 0) {
      System.out.println("Columns don't match maplength");
      System.exit(1);
    }

    int startCount = mapCode.length() - mapCode.replace("S", "").length();

    File mapFile = new File("./" + title.replace(" ", "") + ".json");
    FileWriter fw;
    BufferedWriter bw = null;
    try {
      fw = new FileWriter(mapFile);
      bw = new BufferedWriter(fw);

      bw.write("{\n");
      bw.write("\"name\": \"" + title + "\",\n");

      bw.write("\"author\": \"" + "maks" + "\",\n");
      bw.write("\"cols\": " + cols + ",\n");
      bw.write("\"rows\": " + mapCode.length() / cols + ",\n");

      bw.write("\"players\": " + startCount + ",\n");

      bw.write("\"mapcode\": ");
      bw.write("\"");
      for (int i = 0; i < rows; i++) {
        bw.write(mapCode.substring(i * cols, i * cols + cols));
        bw.write("\\n");
      }
      bw.write("\",\n");

      bw.write("\"cps\": [");
      if (mapCode.contains("1")) {
        bw.write("1");
      }
      for (int i = 2; i <= 9; i++) {
        if (mapCode.contains(String.valueOf(i))) {
          bw.write(", " + i + "");
        }
      }
      bw.write("]\n");
      bw.write("}");
    } catch (IOException e) {
      e.printStackTrace();
    } finally {
      try {
        bw.close();
      } catch (IOException e) {
        e.printStackTrace();
      }
    }
  }

}
