package org.racetrack.game;

import java.util.*;

import org.eclipse.collections.impl.list.mutable.*;

public class GameTitles {

  public static List<String> titles = new FastList<>();

  static {
    titles.add("Snakes On A Plane");
    titles.add("Temple of Doom");
    titles.add("The Adventures of Buckaroo Bonzai across the 8th Dimension");
    titles.add("Don't be a Menace in South Central while drinking your Juice in the Hood");
    titles.add("Fried Green Tomatoes at the Whistle Stop Cafe");
    titles.add("My Stepmother is an Alien");
    titles.add("The Milagro Beanfield War");
    titles.add("The Three Burials of Melquiades Estrada");
    titles.add("To Wong Foo, thanks for everything, Julie Newmar");
    titles.add("I'm Gonna Git You Sucka");
    titles.add("Eight heads in a duffel Bag");
    titles.add("Joe Versus The Volcano");
    titles.add("Countdown to liquor day");
    titles.add("Killer Klowns from outer Space");

    titles.add("Meine Freunde nennen mich Lenny. Aber ich habe keine Freunde.");
    titles.add("Setz Dich, nimm dir 'n Keks, mach es Dir schön bequem ... Du Arsch!");
    titles.add("Geh nicht weg - wir haben die selbe Blutgruppe!");
    titles.add("Habe ich schon 'Danke' gesagt?  Nein. Kommt noch!");
    titles.add("Ich spuck dir in die Augen und blende dich!");
    titles.add("Ich hab' es genau beobachtet: Rot: stehen bleiben, Grün: fahren und Gelb: schneller fahren.");
    titles.add("Wo ist das verdammte Geld, Lebowski?");
    titles.add("Colonel!! Wenn ich nicht wüsste, Sie waren's, würde ich sagen, Sie sind's!");
    titles.add("Was zur Hölle ist ein Woogy?");
    titles.add("Die Rosen sind rot, die Veilchen sind blau, ich bin schizophren und das bin ich auch.");
    titles.add("Waynes World, Waynes World, party time, excelent!");
    titles.add(
        "Du bist in der Hölle kleiner Mann, und ich bin der Teufel! - Du bist nicht der Teufel. Du bist Training!");
    titles.add(
        "Lagerraum 9 hat sich letzte Woche selbst zerstört und den gesamten Klopapiervorrat des Schiffes vernichtet...");
    titles.add("Warum bin ich Mr. Pink? Ich will nicht Mr. Pink sein!");
    titles.add("Was ist das? Blaues Licht! Und was macht es? Es leuchtet blau!");
    titles.add("Die Schlüssel sind weggelaufen.");
    titles.add("Wenn es blutet, kann man es töten");
    titles.add("Was sind Tüften, mein Schatz? Kar-tof-feln! Man kocht sie, man stampft sie, man tut sie in die Suppe.");
    titles.add("Das ist Sparta!!!");
    titles.add("You talkin to me? Well, Im the only one here");
    titles.add(
        "Sie brauchen mir nicht ständig zuzustimmen: Solange nichts anderes bewiesen ist, gehen wir einfach davon aus, dass ich recht habe!");
    titles.add("Dumm ist der, der dummes tut");
    titles.add("I always tell the truth. Even when i lie.");
    titles.add("Durch die Tür hinaus, zur linken Reihe, jeder nur ein Kreuz.");

    titles.add("Ich darf keine Kreide verschwenden.");
    titles.add("Ich darf nicht im Flur Skateboard fahren.");
    titles.add("Ich darf nicht in der Klasse rülpsen.");
    titles.add("Ich darf keine Revolution anzetteln.");
    titles.add("Ich darf im Unterricht keine nackten Frauen zeichnen.");
    titles.add("Ich habe nicht Elvis gesehen.");
    titles.add("Ich darf meine Lehrerin nicht \"heißes Gerät\" nennen.");
    titles.add("Knoblauch-Kaugummi ist nicht lustig.");
    titles.add("Sie lachen über mich, nicht mit mir.");
    titles.add("Ich darf in einem überfüllten Klassenzimmer nicht \"Feuer\" rufen.");
    titles.add("Ich darf andere nicht zum Fliegen verleiten.");
    titles.add("Teer ist kein Spielzeug.");
    titles.add("Ich werde keine Kopien von meinem Hintern machen.");
    titles.add("Ich darf meine Hosen nicht mir anderen tauschen.");
    titles.add("Ich bin keine 32-jährige Frau.");
    titles.add("Ich darf das nicht mit meiner Zunge machen.");
    titles.add("Ich darf nicht das Auto des Rektors fahren.");
    titles.add("Ich darf Bart nicht anbeten.");
    titles.add("Ich darf kein Schuleigentum verkaufen.");
    titles.add("Ich darf meine Arbeit nicht abkürzen.");
    titles.add("Mit dieser Einstellung komme ich nicht weit.");
    titles.add("Ich muss im Klassenzimmer meine Blähungen unterdrücken.");
    titles.add("Ich darf nicht die Nationalhymne rülpsen.");
    titles.add("Ich darf keine Grundstücke in Florida verkaufen.");
    titles.add("Ich darf die Kletterstange nicht einfetten.");
    titles.add("Ich darf meine Gemeinheiten nicht verheimlichen.");
    titles.add("Ich darf nie wieder etwas Böses tun.");
    titles.add("Ich darf nicht angeben.");
    titles.add("Ich darf nicht während der Schulstunde schlafen.");
    titles.add("Ich bin kein Zahnarzt.");
    titles.add("Spucken hat nichts mit Meinungsfreiheit zu tun.");
    titles.add("Wer anderen auf den Sonnenbrand schlägt ist unbeliebt.");
    titles.add("Sprengstoff gehört nicht in die Schule.");
    titles.add("Ich soll nicht mit der Kreide quietschen.");
    titles.add("Was man anfängt, bringt man zu En...");
    titles.add("Bart-Dollar sind kein legales Zahlungsmittel.");
    titles.add("Hamster können nicht fliegen.");
    titles.add("Unterwäsche trägt man unter der Wäsche.");
    titles.add("Der Weihnachtsumzug ist nicht beknackt.");
    titles.add("Seelisch Schwache quält man nicht.");
    titles.add("Ich darf keine Götter schnitzen.");
    titles.add("Ich darf andere nicht verhauen.");
    titles.add("Ich darf nicht auf Köpfe zielen.");
    titles.add("Mich würgt es nur noch, wenn ich krank bin.");
    titles.add("Ich hab im Lehrerzimmer nichts Ungewöhnliches gesehen.");
    titles.add("Ich darf nicht eigenmächtig Probealarm geben.");
    titles.add("Meine komischen Geräusche sind nicht komisch.");
    titles.add("Schildkröten sind keine Kreisel.");
    titles.add("Ich lasse nie wieder BHs schnippen.");
    titles.add("Ich darf keine Schlaganfälle vortäuschen.");
    titles.add("Diese Bestrafung ist nicht ärgerlich und sinnlos.");
    titles.add("Ich heiße nicht Dr. Tod.");
    titles.add("Ich darf New Orleans nicht mies machen.");
    titles.add("Ich darf keine Medikamente verschreiben.");
    titles.add("Ich darf das neu eingeschulte Kind nicht vergraben.");
    titles.add("Ich darf anderen nicht das Fliegen beibringen.");
    titles.add("Ich darf keine Schafe in die Klasse bringen.");
    titles.add("Ein Rülpser ist keine Antwort.");
    titles.add("Ein Lehrer ist kein Aussätziger.");
    titles.add("Kaffee ist nichts für Kinder.");
    titles.add("Ich darf keine Sachen essen, nur weil ich dafür bezahlt werde.");
    titles.add("Ich darf beim Namensaufruf nicht dazwischen schreien: \"Sie ist tot\".");
    titles.add("Das Toupee des Rektors ist kein Frisbee.");
    titles.add("Ich darf den Rektor nicht \"Kartoffelkopf\" nennen.");
    titles.add("Goldfische klipsen beim werfen nicht.");
    titles.add("Dreck gehört nicht zu den vier Grundnahrungsmitteln.");
    titles.add("Niemand interessiert sich für meine Unterhose.");
    titles.add("Ich darf keine Wunderkuren verkaufen.");
    titles.add("Ich muss den Blindenhund zurück bringen.");
    titles.add("Ich genieße keine diplomatische Immunität.");
    titles.add("Ich darf kein Eintrittsgeld fürs Klo verlangen.");
    titles.add("Ich werde nie einen Emmy gewinnen.");
    titles.add("Die Cafeteria-Friteuse ist kein Spielzeug.");
    titles.add("Nur arbeiten und nie spielen macht Bart stumpfsinnig.");
    titles.add("Ich sage nicht \"Springfield\" nur um Applaus zu bekommen.");
    titles.add("Ich bin nicht berechtigt, Aushilfslehrer zu feuern.");
    titles.add("Meine Hausaufgaben wurden nicht von einem Einarmigen gestohlen.");
    titles.add("Ich halte mich von der Kindergarten-Schildkröte fern.");
    titles.add("Ich bin nicht entzückend unverschämt.");
    titles.add("Organtransplantationen überlässt man am besten den Profis.");
    titles.add("Das amerikanische Treuegelöbnis endet nicht mit den Worten \"Heil Satan\".");
    titles.add("Ich darf keine sinnlosen Meilensteine feiern.");
    titles.add("Der Lappen muss nicht immer hochgehen.");
    titles.add(
        "Ich werde keine aufgezeichneten Baseballspiele senden ohne die ausdrückliche Erlaubnis der Baseball-Oberliga.");
    titles.add("Fünf Tage auf eine Waffe warten ist nicht zu lang.");
    titles.add("Nicht jedes Böhnchen gibt ein Tönchen.");
    titles.add("Niemand interessiert sich für meine Unterhosen.");
    titles.add("Ich werde keine Abkürzungen benutz.");
    titles.add("Ich bin nicht die Reinkarnation von Sammy Davis Jr.");
    titles.add("Ich darf kein Schmalz mit der Post schicken.");
    titles.add("Ich darf nicht ohne Anordnung Dinge zerlegen.");
    titles.add("Ich darf keine Stempel aus Seife schnitzen.");
    titles.add("Meine Hausaufgaben wurden nicht von einem Einarmigen gestohlen.");
    titles.add("Ralph wird sich nicht verformen, wenn man ihn kräftig quetscht.");
    titles.add("Der Zusatz \"war nur n Scherz\" macht eine Beleidigung des Rektors nicht ungeschehen.");
    titles.add("\"Plastiktütenpenner\" ist kein anerkannter Beruf.");
    titles.add("Die Kursiv-Schrift hat nicht die Bedeutung, die ich immer erwartet habe.");
    titles.add("Beim nächsten Mal könnte ich das sein auf dem Baugerüst.");
    titles.add("Ich werde mir keine Donuts um den Hals hängen.");
    titles.add("Ich werde nicht vergessen meine Tabletten zu nehmen.");
    titles.add("Ich darf mich nicht so aufführen, als ob mir der Laden gehörte.");
    titles.add("Der gutmütige Mensch kann nur so weit getrieben werden.");
    titles.add("Ich habe keine Vollmacht für Erstklässler.");
    titles.add("Nervengas ist kein Spielzeug.");
    titles.add("Ich werde Mrs. Dummvisage nicht verspotten.");
    titles.add("Der erste Zusatzparagraph zur Verfassung beinhaltet nicht rülpsen.");
    titles.add("Das ist kein Anhaltspunkt... oder doch?");
    titles.add("Ich werde mich nicht über die Aufklärung beschweren, wenn ich sie höre.");
    titles.add("\"Verhext sein\" fördert den Satanismus nicht.");
    titles.add("Niemand will was von meiner Achselhöhle wissen.");
    titles.add("Ich bin keine mies-gemeine Spuckmaschine.");
    titles.add("Das Jungszimmer ist kein Wasserpark.");
    titles.add("Indianische Verbrennungen gehören nicht zu unserem kulturellen Erbe.");
    titles.add("Stöckelschuhe sind ungesund für Kinder und andere Lebewesen.");
    titles.add("Ich darf das nur einmal im Jahr machen.");
    titles.add("Ich werde aufhören, über den Dreißigzentimeterpianisten zu reden.");
    titles.add("Ich bin nicht berechtigt, Asbest zu entfernen.");
    titles.add("Nicht alles, was ich wissen muss, hab ich im Kindergarten gelernt.");
    titles.add("Ich bin nicht mein lange verschollener Zwilling.");
    titles.add("Die Wahrheit liegt nicht draußen auf der Straße.");
    titles.add("Ich habe nicht die Erlaubnis, etwas zu tun.");
    titles.add("Ich darf nicht die Prozac meines Lehrers verstecken.");
    titles.add("Eine Feuerübung erfordert kein Feuer.");
    titles.add("Ich will nicht mehr MTV sehen.");
    titles.add("Alle haben diese Richard Gere-Geschichte endgültig satt.");
    titles.add("Ich hab keine irischen Tänze erfunden.");
    titles.add("Ich darf Fettsäcke nicht ärgern.");
    titles.add("Es gab keinen römischen Gott namens \"Furzibus\".");
    titles.add("Rudolphs rote Nase ist nicht alkoholbedingt.");
    titles.add("Farbbeutel werfen ist keine Kunstform.");
    titles.add("Schmerzen sind kein Entschuldigungsmittel.");
    titles.add("'N blöder Bindfaden ist kein Nasenspray.");
    titles.add("Ich hatte nicht den Auftrag, das zu tun.");
    titles.add("Mein Hintern verdient keine Website.");
    titles.add("Ich werde nicht verlangen, was ich wert bin.");
    titles.add("Ich werde die Anfangssequenzen nicht durcheinander bringen.");
    titles.add("Ich bin nicht der neue Dalai Lama.");
    titles.add("Ich war nicht der Denkanstoß für \"Kramer\".");
    titles.add("Ich darf keine frivolen Strafanträge einreichen.");
    titles.add("Treehouse of Horror IX(mit Blut geschrieben)");
    titles.add("arsch.com ist nicht meine E-Mail Adresse.");
    titles.add("Niemand interessiert es, was meine Definition von \"ist\" ist.");
    titles.add("Ich werde nicht nach Eiscreme schreien.");
    titles.add("Ich bin kein zugelassener Friseur.");
    titles.add("\"Der Präsident hat es auch getan\" ist keine Entschuldigung.");
    titles.add("Meine Mutter ist nicht die Freundin von Jerry Seinfeld.");
    titles.add("Sherri hat sich nicht gerächt.");
    titles.add("Ich werde hier nicht den Sündenbock spielen.");
    titles.add("Niemand will was von meinem Ischias wissen.");
    titles.add("Hinterwäldler sind auch Menschen.");
    titles.add("Grammatik ist keine Zeit der Verschwendung.");
    titles.add("Ich habe keine diplomatische Immunität.");
    titles.add("Es ist garnicht so schlimm, du zu sein.");
    titles.add("Ich kann keine Sünden vergeben.");
    titles.add("Ein trainierter Affe kann keinen Sportunterricht geben.");
    titles.add("Lockeren Zähnen braucht man nicht mehr nachzuhelfen.");
    titles.add("Ich war weder dort noch hab ich's getan.");
    titles.add("Niemand will was von meinen Achselhöhlen wissen.");
    titles.add("Ich bin unheimlich müde.");
    titles.add("Auch freitags herrscht Hosenpflicht.");
    titles.add("Schwein ist kein Zeitwort.");
    titles.add("Ich bin nicht der letzte Pate.");
    titles.add("Ich habe nicht den Furz-Nobelpreis gewonnen.");
    titles.add("Ich werde keine doppelte Verneinung nicht benutzen.");
    titles.add("Indianische Brandmale sind nicht unser kulturelles Erbe.");
    titles.add("Ich kann keine Toten sehen.");
    titles.add("Ich werde meine Niere nicht über eBay verkaufen.");
    titles.add("Ich darf aus Mist keine Kunst machen.");
    titles.add("Ich werde aufhören herumzutelefonieren.");
    titles.add("Klassenclown ist kein bezahlter Beruf.");
    titles.add("Vertretungslehrer sind keine Streikbrecher.");
    titles.add("Mein Schulausschluss beruhte nicht auf Gegenseitigkeit.");
    titles.add("Ein Rülpser ist kein mündlicher Bericht.");
    titles.add("Flunkereien bleiben in der Turnhalle vor der Tür.");
    titles.add("Die Aufschrift \"Nicht brennbar\" ist keine Herausforderung.");
    titles.add("Da wurde ich nicht von einem Engel berührt.");
    titles.add("Ich bin nicht auf Grund eines Furzballstipendiums hier.");
    titles.add("Ich werde keinesfalls auf einem Grab tanzen.");
    titles.add("Ich darf keinen Ersatzstudenten engagieren.");
    titles.add("Ich werde den Stimmen in meinem Kopf nicht gehorchen.");
    titles.add("Ich darf keine unterschwelligen Botschaften implantieren.");
    titles.add("Ich darf die Unkeuschheit nicht überrumpeln.");
    titles.add("Ich bin nicht der amtierende Präsident.");
    titles.add("Ich war nicht der sechste Beatle.");
    titles.add("Ich liefere nur eine Urinprobe ab, wenn ich darum gebeten werde.");
    titles.add("Die Krankenschwester ist keine Dealerin.");
    titles.add("Der Physikunterricht soll nicht in einer Tragödie enden.");
    titles.add("Terrestrisches Fernsehen ist nicht tot.");
    titles.add("Ich werde nicht die Hunde rauslassen.");
    titles.add("Ich darf die Medikamente des Lehrers nicht verstecken.");
    titles.add("Ich werde nicht das Führungszeugnis des Rektors veröffentlichen.");
    titles.add("Ein Hamster hat kein vollkommenes Leben.");
    titles.add("Ich bin mit dem Straferlass eines Präsidenten nicht einverstanden.");
    titles.add("\"Temptation Island\" war kein billiges Machwerk.");
    titles.add("Ich darf den Vizepräsidenten nicht erschrecken.");
    titles.add("Ich darf keine Beweise wegspülen.");
    titles.add("Feuer ist kein Reinigungsmittel.");
    titles.add("Vererbungslehre ist keine Ausrede.");
    titles.add("Heute ist nicht Mothra-Tag.");
    titles.add("Ich sollte jetzt noch nicht 21 sein.");
    titles.add("Niemand liest die mehr.");
    titles.add("Ein Rülpser in einem Glas ist kein wissenschaftliches Projekt.");
    titles.add("Spaß hat keine Größe.");
    titles.add("Ich bin nicht Charlie Brown auf nem LSD-Trip.");
    titles.add("Ich habe keine Corn Flakes die nach mir benannt sind.");
    titles.add("Ich werde nicht die Hand beißen die mich mit Butterfingern füttert.");
    titles.add("Der Baum des Gebens ist kein grober Klotz.");
    titles.add("Milhouse zum Weinen bringen ist kein wissenschaftliches Projekt.");
    titles.add("Vampir sein ist keine Karrierewahl.");
    titles.add("Fische mögen keinen Kaffee.");
    titles.add("Milhouse wurde nicht Läuse-positiv getestet.");
    titles.add("Diese Schule braucht keinen Regimewechsel.");
    titles.add("Ein Schwamm ist kein Empfängnisverhütungsmittel.");
    titles.add("Mein Schreibheft ist keine Popel-Startrampe.");
    titles.add("Sandwiches sollten keinen Sand enthalten.");
    titles.add("Über 40, noch Solo ist nicht witzig.");
    titles.add("Ich will nicht grübeln, wie scharf die Lehrer mal waren.");
    titles.add("Einen toten Waschbären rumschubsen ist keine wissenschaftliche Untersuchung.");
    titles.add("Bier in ner Milchtüte ist keine Milch.");
    titles.add("Ein Popel ist kein Lesezeichen.");
    titles.add("Macht irgendein Kind das überhaupt noch?");
    titles.add("Ich bin nicht klüger als der Präsident.");
    titles.add("Der Lehrer wurde nicht rausgeschmissen - es beruhte auf Gegenseitigkeit.");
    titles.add("Ich darf das Klassenzimmer nicht auf den Kopf stellen.");
    titles.add("Ich darf die Handlung des Films nicht vorher verraten.");
    titles.add("Je ne parle pas francais.");
    titles.add("Wir sind nicht alle nackt unter unserer Kleidung.");
    titles.add("Frankenwein ist kein Monster.");
    titles.add("Die globale Erwärmung hat meine Hausaufgaben nicht gefressen.");
    titles.add("Ich werde mich nicht darüber informieren was ein Lehrer verdient.");
    titles.add("Perlen sind keine Austernkotze.");
    titles.add("Ich werde keine 20 Jahre warten, um wieder einen Film zu machen.");
    titles.add("Ich bin keine beim \"Staatlichen-Einlagen-Versicherungs-Fond\" versicherte Bank.");
    titles.add("Sowas wie einen iPoddy gibt es nicht.");
    titles.add("Die Pilger waren keine illegalen Einwanderer.");
    titles.add("Die Hauptstadt von Montana ist nicht \"Hannah\".");
    titles.add("Die Lehrerin hat nicht zu viel für ihre Eigentumswohnung gezahlt.");
    titles.add("Die Kunstlehrerin ist fett, nicht schwanger.");
    titles.add("Ein Mensch ist ein Mensch, egal wie Ralph er ist.");
    titles.add("Diese Bestrafung ist nicht mittelalterlich.");
    titles.add("Die Diät der Lehrerin funktioniert doch.");
    titles.add("Es gibt keinen Monat namens \"Rocktober\".");
    titles.add("Ich habe nicht gesehen, wie der Lehrer Benzin abgesaugt hat.");
    titles.add("Der Wohlstand wartet nur um die Ecke.");
    titles.add("Jesus ist nicht sauer, dass sein Geburtstag an Weihnachten ist.");
    titles.add("Ich werde keine wasserfeste Tinte an der Tafel verwenden.");
    titles.add("HDTV ist jeden Cent wert.");
    titles.add("Basketballfieber ist kein Grund, nicht in die Schule zu gehen.");
    titles.add("Ich werde keinen Spaß mit Lernspielzeugen haben.");
    titles.add("Vierblättrige Kleeblätter sind keine mutierten Freaks.");
    titles.add("Mein Sparschwein erhält nichts vom Finanzmarkt-Stabilisierungsfond.");
    titles.add("Ich werde mich nicht über das veraltete Handy des Lehrers lustig machen.");
    titles.add("Ich werde keine Chili-Sauce in die 'Erste-Hilfe Puppe' füllen.");
    titles.add("Es heißt “Facebook”, nicht “Arschbook”.");
    titles.add("Der Klassenhamster schläft nicht einfach nur.");
    titles.add("Strafarbeit ist keine Folter.");
    titles.add("Ich bin nicht allergisch gegen schriftliche Division.");
    titles.add("Ich stehe nicht auf meine Mom.");
    titles.add("Halloween ist nicht so geil wie Thanksgiving.");
    titles.add("Lehrer Gewerkschaften sind nicht zum ruinieren des Landes da.");
    titles.add("Die Welt endet vielleicht 2012, aber diese Serie nicht.");
    titles.add("Der zweite Weltkrieg könnte den ersten nicht platt machen.");
    titles.add("Hot Dogs sind keine Lesezeichen.");
    titles.add("Das zählt als Sport- und Kunststunde.");
    titles.add("Je ne suis pas français.");
    titles.add("Dass ich mein Gemüse esse ist kein Muttertagsgeschenk.");
    titles.add("Batman ist nicht \"nichts ohne seinen Bat-Gürtel\".");
    titles.add("Lost ist vorbei; der Hund hat alles geträumt. Schaut uns!");
    titles.add("Ich hab im Unterricht nicht geschlafen, um Leonardo DiCaprio zu helfen.");
    titles.add("Ich habe nicht gesehen, wie die Lehrerin Sozialhilfe beantragt hat.");
    titles.add("Ich darf nicht alle Wände beschmieren.");
    titles.add("\"Thanksgiving mit Charlie Brown\" ist genauso gut wie \"Weihnachten mit Charlie Brown\".");
    titles.add("Zuckerstangen sind keine Elfenknochen.");
    titles.add("Januar ist nicht der Bart-Geschichts-Monat.");
    titles.add("Ich werde keine Witze über den Schniepel von Amor machen.");
    titles.add("Ich bin nicht wegen eines Spuckebällchen Stipendiums hier.");
    titles.add("Ich werde mich nicht über die Basketball-Kenntnisse meiner Lehrerin lustig machen.");
    titles.add("Man sollte Meerschweinchen nicht als Versuchskaninchen benutzen.");
    titles.add("\"Auschuß\" ist kein schmutziges Wort.");
    titles.add("Cafeteria-Tabletts sind keine Schlitten.");
    titles.add("Tim und Struppi sind nicht Schlimm und Juppi.");
    titles.add("Wir brauchen keine Bildung nicht.");
    titles.add("Es wurde nie eine Verbindung zwischen Rosinen und Popeln nachgewiesen.");
    titles.add("Ich werde keine Zuckerherzen mit Froschherzen vertauschen.");
    titles.add("Bart hat sich einen freien Tag verdient.");
    titles.add("Die Lehrerin muss keine Häßlichkeitssteuer zahlen.");
    titles.add("Ruf deine Mutter in der Werbepause an.");
    titles.add("Ich akzeptiere das Wahlergebnis erst, wenn die Republikaner es mir erlauben.");
    titles.add("Ich möchte staatliche Unabhängigkeit, weiß aber nicht in welchem Staat ich bin.");
    titles.add("Noch 20 Tage Ladendiebstahl bis Weihnachten.");
    titles.add("Die Lehrerin ist in den Ferien nicht fett geworden.");
    titles.add("Ich werde mich ab jetzt bei der Oscar-Verleihung an die Regeln halten.");
    titles.add("Ich wurde nicht für das \"Beste Schimpfwort\" nominiert.");
    titles.add("Ich werde nicht als Klo vom Rektor twittern.");
    titles.add("Es tut mir leid, dass ich die Tafel kaputt gemacht habe.");
    titles.add("Die letzten Worte von Jesus waren nicht \"Gottseidank ist es Freitag\".");
    titles.add("25 Jahre und ihnen fällt keine neue Bestrafung ein.");
    titles.add("Was du heute kannst besorgen, das verschiebe nicht auf morgen.");
    titles.add("(mit trauriger Stimme) Wir werden sie wirklich vermissen, Mrs. K.");
    titles.add("In meiner Schule ist niemals spielfrei.");
    titles.add("Wenn du deine Weihnachtsgeschenke bis jetzt nicht kaputt gemacht hast, strengst du dich nicht an.");
    titles.add("Bart malt einen Turnierplan an die Tafel.");
    titles.add("Mein Dad ist schon besoffen für den St. Patricks Day.");
    titles.add("Man darf am 27. April keine Aprilscherze machen");
    titles.add("Spoiler-Alarm: Mein Dad stirbt leider nicht.");
    titles.add("Rentierfleisch schmeckt nicht wie Hühnchen.");
    titles.add("Schneemänner haben keinen Karottenpenis.");
  }

  public static String getRandomTitle() {
    Random randomizer = new Random();
    return titles.get(randomizer.nextInt(titles.size()));
  }

}
